### ISSUE TITLE
Update sampling and modeling to predict 2D outputs

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/naip-cnn#5]
Currently we predict scalar forest metrics from 2D NAIP arrays, essentially using our CNN as a classifier where the label is a continuous forest measurement. This setup restricts the size of input chips we can use to our spatial resolution, e.g. if we want to predict canopy cover at 30m, our 1m NAIP array *must* be 30x30. The model may benefit from the additional context provided by a larger image, e.g. 256x256, but this will require us to predict 2D arrays of forest metrics rather than scalars, effectively changing this problem from image classification to semantic segmentation.

To make that adjustment, the sampling will need to be updated to extract and store 2D arrays from the LiDAR rasters, rather than single values. The only substantial challenge there should be ensuring that our LiDAR pixel array exactly matches the footprint of the NAIP array. Additionally, the model architecture will need to be adjusted to a fully-connected CNN.

With those changes, we can decouple our image size from our output spatial resolution, allowing us to predict at arbitrary image sizes and spatial resolutions by adjusting the array shapes.

**Comment by grovduck** [comment]
@aazuspan, as I mentioned this sounds really cool.  I'm all in favor of this approach, especially as a comparison point with the classification approach.
